### PR TITLE
Added template notebooks for deployment

### PR DESCRIPTION
**Pull request by sssangha**
Example notebooks for deployment over Tibet track with multiple AOIs.

Note that all the parameters a user needs to toggle are exposed in the first block.

These notebooks now support a spatiotemporal check, whereby scenes over the AOI are grouped into spatiotemporally contiguous sets. Scenes which contain gaps (i.e. missing frame(s)) or do not maintain a minimum specified threshold of overlap WRT to the input AOI are also discarded. This is meant to ensure the common intersection of all pairs down-stream will have great coverage over the AOI as expected.

Pay particular attention to the `df_pairs_dict = pair_spatial_check(df_pairs, aoi, azimuth_mismatch=azimuth_mismatch)` block and the detailed message above. To recap here, this is the sanity check step whereby pairs generated from the queried SLCS (which as explained above were vetting for spatiotemporal continuity) are in turn vetted for spatiotemporal continuity. No pairs should be flagged. If they are, either there is an unresolved bug or the spatial threshold constraint is too liberal.

This notebook is dependent on the complementary PR#12 for `s1_enumerator` repo (https://github.com/ACCESS-Cloud-Based-InSAR/s1-enumerator/pull/12)

### CODE REVIEW

**Comment by sssangha** [comment]
@gracebato please take one of these notebooks and test on your other case study. Note again that they are both the same, aside for different specified AOI paths in the top block.

**Comment by dbekaert** [comment]
@sssangha What is the difference between notebook A and B. Please clarify which one @gracebato should be looking at.

**Comment by sssangha** [comment]
@gracebato you could look at either. Only difference again is the shapefile at the top section which is changed.
Let's just say look at A then.

**Comment by sssangha** [comment]
@gracebato following our conversation, I made some changes to query the tiles independently of a user-specified start-date in the beginning. Tiles are now queried directly over the entire AOI instead of relying on a specified start-date reference scene.

However, these changes are dependent on a complementary PR in the s1-enumerator repo (https://github.com/ACCESS-Cloud-Based-InSAR/s1-enumerator/pull/13). Specifically, the max number of results was originally restricted and thus cutting off the expected number of tiles. This limit has been relaxed in the aforementioned PR to ensure this isn't an issue.

**Pull request merged**
